apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: teste-replicaset
spec:
  template:
    metadata:
      name: primeiro-pod
      labels: 
        app: primeiro-pod
    spec:
      containers:
        - name: test
          image: nginx:1.14.2
          ports:
          - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: primeiro-pod