apiVersion: v1
kind: Service
metadata:
  name: svc-redis
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: sfs-redis
  ports:
    - name: svc-redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  